version: "3.8"
services: 

  postgres:
    image: postgres:15-alpine
    container_name: kreptkon-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kreptkon
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d kreptkon"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-api: 
    build: ./backend
    container_name: krepkton-flask
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/kreptkon
      API_VERSION: "2.0-with-database"
      ENVIRONMENT: "development"
      LOG_LEVEL: "INFO"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
    