apiVersion: v1
kind: Secret
metadata:
  name: flask-api-secret
  labels:
    app: flask-api
type: Opaque
data:

  #Passwords have all been encoded in base 64 
  # *To Encode something - echo -n "something" | base64
  # *To Decode sometihng - echo -n "encoded-value" | base64 -d

  DATABASE_PASSWORD: cGFzc3dvcmQxMjM=

  API_KEY: bXktc2VjcmV0LWFwaS1rZXktMTIzNDU=

  JWT_SECRET: and0LXNlY3JldC1rZXktZm9yLXRva2Vucw==