apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-api-config
  labels:
    app: flask-api
data: 
  #Application settings
  API_VERSION: "v1.0"
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"
  MAX_CONNECTIONS: "100"
  FEATURE_FLAG_NEW_UI: "true"

  # Database settings (non-sensitive) for Postgres connection
  DATABASE_HOST: "postgres-service" #kubernetes service dns name
  DATABASE_PORT: "5432" #postgres default
  DATABASE_NAME: "kreptkon" #db created at postgres startup
  DATABASE_USER: "kreptuser" #db user