apiVersion: v1
kind: Secret
metadata:
  name: flask-api-secret
  labels:
    app: flask-api
type: Opaque
data:
  API_KEY: <BASE64_API_KEY>
  JWT_SECRET: <BASE64_JWT_SECRET>


  #Passwords have to be encoded in base 64 
  # *To Encode something - echo -n "something" | base64
  # *To Decode sometihng - echo -n "encoded-value" | base64 -d
